# Generated by Django 4.1.5 on 2023-01-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schrittzaehler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(auto_now_add=True, verbose_name="Datum")),
                ("schritte", models.IntegerField(verbose_name="Anzahl Schritte")),
                (
                    "kalorien",
                    models.IntegerField(verbose_name="Verbrauchte Kalorieren"),
                ),
            ],
        ),
    ]
